import {
  MistralLogo,
  OpenAILogo,
  GeminiLogo,
  AwsLogo,
  AzureLogo,
  AnthropicLogo,
  GroqLogo,
  FireworksLogo,
  DeepseekLogo,
  CohereLogo,
  OllamaLogo,
  XaiLogo,
  AgnoIcon,
  UserIcon,
  AgentIcon,
  SheetIcon,
  NextjsTag,
  ShadcnTag,
  TailwindTag,
  AgnoTag,
  ReasoningIcon,
  ReferencesIcon
} from './custom-icons'
import { IconTypeMap } from './types'
import {
  RefreshCw,
  Edit,
  Save,
  X,
  ArrowDown,
  ArrowLeft,
  SendIcon,
  Download,
  HammerIcon,
  Check,
  ChevronDown,
  ChevronUp,
  Trash,
  Copy,
  List,
  AlertTriangle,
  Clock,
  Moon,
  Sun,
  Eye,
  EyeOff,
  Server,
  Globe,
  Settings,
  MessageCircle,
  Lightbulb,
  Code,
  Rocket,
  Terminal,
  Plus,
  Minus
} from 'lucide-react'

import { PlusIcon } from '@radix-ui/react-icons'

export const ICONS: IconTypeMap = {
  'open-ai': OpenAILogo,
  mistral: MistralLogo,
  gemini: GeminiLogo,
  aws: AwsLogo,
  azure: AzureLogo,
  anthropic: AnthropicLogo,
  groq: GroqLogo,
  fireworks: FireworksLogo,
  deepseek: DeepseekLogo,
  cohere: CohereLogo,
  ollama: OllamaLogo,
  xai: XaiLogo,
  agno: AgnoIcon,
  user: UserIcon,
  agent: AgentIcon,
  sheet: SheetIcon,
  nextjs: NextjsTag,
  shadcn: ShadcnTag,
  tailwind: TailwindTag,
  reasoning: ReasoningIcon,
  'agno-tag': AgnoTag,
  refresh: RefreshCw,
  edit: Edit,
  save: Save,
  x: X,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  send: SendIcon,
  download: Download,
  hammer: HammerIcon,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'plus-icon': PlusIcon,
  references: ReferencesIcon,
  trash: Trash,
  copy: Copy,
  list: List,
  'alert-triangle': AlertTriangle,
  clock: Clock,
  moon: Moon,
  sun: Sun,
  eye: Eye,
  'eye-off': EyeOff,
  server: Server,
  globe: Globe,
  settings: Settings,
  'message-circle': MessageCircle,
  lightbulb: Lightbulb,
  'code-xml': Code,
  rocket: Rocket,
  terminal: Terminal,
  plus: Plus,
  minus: Minus
}
